# Generated by Django 4.1.1 on 2023-02-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recharg",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
